version: '3'


networks:
  sspanel:

volumes:
  mysql_data:

services:
  nginx:
    image: nginx
    restart: always
    container_name : nginx
    volumes:
      - ./configs/nginx/:/etc/nginx/conf.d
      - .:/usr/src/app
    ports:
      - 20000:80
    depends_on:
      - web
    networks:
      - sspanel
  mysql:
    image: mysql:5.6
    container_name : mysql
    restart: always
    env_file:
      - .envs/.production/.mysql
    volumes:
      - ./configs/mysqld/mysqld_charset.cnf:/etc/mysql/conf.d/mysqld_charset.cnf
      - mysql_data:/var/lib/mysql
    networks:
      - sspanel
  web:
    container_name : web
    restart: always
    build: .
    image: sspanel
    env_file:
      - .envs/.production/.django
    volumes:
      - .:/usr/src/app
    depends_on:
      - mysql
    networks:
      - sspanel
    ports:
      - 8080:8080
    working_dir: /usr/src/app
    command: uwsgi uwsgi.ini